apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: eai-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: production
      - op: replace
        path: /data/LOG_LEVEL
        value: INFO
