apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enterprise-ai
resources:
  - namespace-config.yaml
  - data-stores.yaml
  - apps.yaml
  - ingress-netpol.yaml
images:
  - name: ghcr.io/example/eai-backend
    newTag: "0.12.0"
  - name: ghcr.io/example/eai-frontend
    newTag: "0.12.0"
  - name: ghcr.io/example/eai-worker
    newTag: "0.12.0"
